"""Regression tests for access control — Generated by The Lateral v1.2"""

import pytest
from unittest.mock import Mock, patch



# Mock HTTP client for access control testing
class MockResponse:
    def __init__(self, status_code, data=None):
        self.status_code = status_code
        self.data = data or {}

    def json(self):
        return self.data


def create_mock_client(auth_required=True):
    client = Mock()

    def mock_request(method, url, **kwargs):
        headers = kwargs.get("headers", {})
        token = headers.get("Authorization", "")

        if not auth_required:
            return MockResponse(200, {"status": "ok"})

        if not token:
            return MockResponse(401, {"error": "Unauthorized"})

        if "invalid" in token or "expired" in token:
            return MockResponse(403, {"error": "Forbidden"})

        return MockResponse(200, {"status": "ok"})

    client.request = mock_request
    return client


@pytest.mark.parametrize("endpoint", ["/api/data", "/api/admin", "/api/users", "/api/config"])
def test_unauthenticated_access_returns_401(endpoint):
    client = create_mock_client(auth_required=True)
    response = client.request("GET", endpoint, headers={})
    assert response.status_code == 401, f"{endpoint} should reject unauthenticated access"


@pytest.mark.parametrize("endpoint", ["/api/data", "/api/admin"])
def test_invalid_token_returns_403(endpoint):
    client = create_mock_client(auth_required=True)
    response = client.request("GET", endpoint, headers={"Authorization": "Bearer invalid_token"})
    assert response.status_code == 403, f"{endpoint} should reject invalid tokens"


def test_authenticated_access_succeeds():
    client = create_mock_client(auth_required=True)
    response = client.request("GET", "/api/data", headers={"Authorization": "Bearer valid_token"})
    assert response.status_code == 200


def test_public_endpoints_no_auth():
    client = create_mock_client(auth_required=False)
    response = client.request("GET", "/api/health", headers={})
    assert response.status_code == 200, "Health endpoints should not require auth"


@pytest.mark.parametrize("method", ["POST", "PUT", "DELETE", "PATCH"])
def test_mutating_endpoints_require_auth(method):
    client = create_mock_client(auth_required=True)
    response = client.request(method, "/api/data", headers={})
    assert response.status_code == 401, f"{method} /api/data should require auth"


def test_sql_injection_in_token_rejected():
    client = create_mock_client(auth_required=True)
    malicious_token = "' OR 1=1; --"
    response = client.request("GET", "/api/admin", headers={"Authorization": f"Bearer {malicious_token}"})
    assert response.status_code in (401, 403), "Malicious tokens should be rejected"
